config/routes.rb
Rails.application.routes.draw do
  resources :sections do
    resources :lessons
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  validates :number, :presence => true
  validates :name, :presence => true
  validates :content, :presence => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  validates :name, :presence => true
  validates :description, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @section = Section.find(params[:section_id])
    @lessons = Lesson.all
  end

  def show
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  def new
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new
  end

  def create
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      redirect_to section_path(@lesson.section)
      flash[:notice] = "The " + @lesson.name + " was successfully created."
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.find(params[:id])
  end

  def update
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to lesson_path(@lesson)
      flash[:notice] = "The " + @lesson.name + " was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.find(params[:id])
    @lesson.destroy
    redirect_to sections_path
    flash[:notice] = "The " + @lesson.name + " was successfully deleted."
  end

private
  def lesson_params
    params.require(:lesson).permit(:number, :name, :content)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
    @lessons = @section.lessons.all
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to sections_path
      flash[:notice] = @section.name + " was successfully created."
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to section_path(@section)
      flash[:notice] = @section.name + " was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
    flash[:notice] = @section.name + " was successfully deleted."
  end

  private
  def section_params
    params.require(:section).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix the following errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] %>
<%= flash[:alert] %>
<%= yield %>

</body>
</html>

app/views/lessons/_form.html.erb
<%= render 'layouts/errors', :object => @lesson %>

<%= form_for [@section, @lesson] do |f| %>
  <%= f.label :number %>
  <%= f.number_field :number %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<% content_for(:title, "Update Lesson | Learn to Program") %>

<h1>Update This Lesson</h1>

<%= render 'form' %>

app/views/lessons/index.html.erb
<% content_for(:title, "Lessons | Learn to Program") %>

<h1>Lessons</h1>

<ul>
  <% @lessons.each do |lesson| %>
    <li><%= lesson.number %> | <%= link_to lesson.name, lesson_path(lesson) %></li>
  <% end %>
</ul>

<p>
  <%= link_to "Create a New Lesson", new_lesson_path(@lessons) %>
</p>

app/views/lessons/new.html.erb
<% content_for(:title, "New Lesson | Learn to Program") %>

<h1>Create a New Lesson</h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<% content_for(:title, "Lesson | Learn to Program") %>

<h1><%=   @lesson.name %></h1>

<p>
  <%= @lesson.content %>
</p>

<p>
  <%= link_to 'Update this lesson', edit_lesson_path(@lesson) %>
</p>

<p>
  <%= link_to "Delete this lesson", lesson_path(@lesson),
                                    :data => {:confirm => "Are you sure?",
                                              :method => 'delete'} %>
</p>


<p>
  <%= link_to "Next lesson", lesson_path(@lesson) %>
</p>

<p>
  <%= link_to 'Return to lessons list', lessons_path %>
</p>

app/views/sections/_form.html.erb
<%= render 'layouts/errors', :object => @section %>

<%= form_for @section do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<% content_for(:title, "Update Section | Learn to Program") %>

<h1>Update This Section</h1>

<%= render 'form' %>

app/views/sections/index.html.erb
<% content_for(:title, "Sections | Learn to Program") %>

<h1>Sections</h1>

<ul>
  <% @sections.each do |section| %>
  <li><%= link_to section.name, section_path(section) %></li>
  <% end %>
</ul>

<p>
  <%= link_to "Create a New Section", new_section_path(@section) %>
</p>

app/views/sections/new.html.erb
<% content_for(:title, "New Section | Learn to Program") %>

<h1>Create a New Section</h1>

<%= render 'form' %>

app/views/sections/show.html.erb
<% content_for(:title, "Section | Learn to Program") %>

<h1><%=   @section.name %></h1>

<p>
  <%= @section.description %>
</p>

<h4>Lessons in this Section</h4>

<ul>
  <% @section.lessons.each do |lesson| %>
  <li><%= lesson.number %> | <%= link_to lesson.name, section_lesson_path %></li>
  <% end %>
</ul>

<p>
  <%= link_to "Create a New Lesson", new_section_lesson_path(@section) %>
</p>

<p>
  <%= link_to 'Update this section', edit_section_path(@section) %>
</p>

<p>
  <%= link_to "Delete this section", section_path(@section),
                                          :data => {:confirm => "Are you sure?",
                                                    :method => 'delete'} %>
</p>

<p>
  <%= link_to 'Return to sections list', sections_path %>
</p>